//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R2D2_DemoDay_EvanFormFramework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("R2D2_DemoDay_EvanFormFramework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CS {
            get {
                object obj = ResourceManager.GetObject("CS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CS_TRANSPARENT {
            get {
                object obj = ResourceManager.GetObject("CS_TRANSPARENT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CS_TRANSPARENT_1 {
            get {
                object obj = ResourceManager.GetObject("CS_TRANSPARENT_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CS_Transparent_1_1 {
            get {
                object obj = ResourceManager.GetObject("CS_Transparent_1-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CS_Transparent_1_1__1_ {
            get {
                object obj = ResourceManager.GetObject("CS_Transparent_1-1 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CS_Transparent_10_1 {
            get {
                object obj = ResourceManager.GetObject("CS_Transparent_10-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CS_Transparent_2_1 {
            get {
                object obj = ResourceManager.GetObject("CS_Transparent_2-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CS_Transparent_3_1 {
            get {
                object obj = ResourceManager.GetObject("CS_Transparent_3-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CS_Transparent_4_1 {
            get {
                object obj = ResourceManager.GetObject("CS_Transparent_4-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CS_Transparent_5_1 {
            get {
                object obj = ResourceManager.GetObject("CS_Transparent_5-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CS_Transparent_6_1 {
            get {
                object obj = ResourceManager.GetObject("CS_Transparent_6-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CS_Transparent_7_1 {
            get {
                object obj = ResourceManager.GetObject("CS_Transparent_7-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CS_Transparent_8_1 {
            get {
                object obj = ResourceManager.GetObject("CS_Transparent_8-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CS_Transparent_9_1 {
            get {
                object obj = ResourceManager.GetObject("CS_Transparent_9-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CS_TRANSPARENT1 {
            get {
                object obj = ResourceManager.GetObject("CS_TRANSPARENT1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are active alarms.
        /// </summary>
        internal static string IDS_ACTIVE_ALARMS {
            get {
                return ResourceManager.GetString("IDS_ACTIVE_ALARMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRRobotDemoCSharp - .
        /// </summary>
        internal static string IDS_APP_NAME {
            get {
                return ResourceManager.GetString("IDS_APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string IDS_AVAILABLE {
            get {
                return ResourceManager.GetString("IDS_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t make the selected program invisible.
        /// </summary>
        internal static string IDS_CANT_INV_SELETED {
            get {
                return ResourceManager.GetString("IDS_CANT_INV_SELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string IDS_CLEAR {
            get {
                return ResourceManager.GetString("IDS_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        internal static string IDS_CONFIG {
            get {
                return ResourceManager.GetString("IDS_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string IDS_CONNECTED {
            get {
                return ResourceManager.GetString("IDS_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        internal static string IDS_CONNECTING {
            get {
                return ResourceManager.GetString("IDS_CONNECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed.
        /// </summary>
        internal static string IDS_CONNECTION_FAILED {
            get {
                return ResourceManager.GetString("IDS_CONNECTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not see task status = run.
        /// </summary>
        internal static string IDS_DID_NOT_SEE_PGM_RUN {
            get {
                return ResourceManager.GetString("IDS_DID_NOT_SEE_PGM_RUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string IDS_DISCONNECTED {
            get {
                return ResourceManager.GetString("IDS_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting.
        /// </summary>
        internal static string IDS_DISCONNECTING {
            get {
                return ResourceManager.GetString("IDS_DISCONNECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing .
        /// </summary>
        internal static string IDS_EDITING {
            get {
                return ResourceManager.GetString("IDS_EDITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the program&apos;s name.
        /// </summary>
        internal static string IDS_ENTER_PGM_NAME {
            get {
                return ResourceManager.GetString("IDS_ENTER_PGM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a variable name:.
        /// </summary>
        internal static string IDS_ENTER_VAR_NAME {
            get {
                return ResourceManager.GetString("IDS_ENTER_VAR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string IDS_FALSE {
            get {
                return ResourceManager.GetString("IDS_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find an Invisible Program.
        /// </summary>
        internal static string IDS_FIND_INV_PGM {
            get {
                return ResourceManager.GetString("IDS_FIND_INV_PGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first locial number cannot be modified..
        /// </summary>
        internal static string IDS_FIRST_LOGICAL_NUM_IS_READONLY {
            get {
                return ResourceManager.GetString("IDS_FIRST_LOGICAL_NUM_IS_READONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error raised fron FRCConfigs.Add method:.
        /// </summary>
        internal static string IDS_FRCIOCONFIGS_ADD_ERROR {
            get {
                return ResourceManager.GetString("IDS_FRCIOCONFIGS_ADD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group.
        /// </summary>
        internal static string IDS_GROUP {
            get {
                return ResourceManager.GetString("IDS_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to groups.
        /// </summary>
        internal static string IDS_GROUPS {
            get {
                return ResourceManager.GetString("IDS_GROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heartbeat Lost.
        /// </summary>
        internal static string IDS_HEARTBEAT_LOST {
            get {
                return ResourceManager.GetString("IDS_HEARTBEAT_LOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jog Frames.
        /// </summary>
        internal static string IDS_JOG_FRAMES {
            get {
                return ResourceManager.GetString("IDS_JOG_FRAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KARELProgram.
        /// </summary>
        internal static string IDS_KAREL_PROGRAM {
            get {
                return ResourceManager.GetString("IDS_KAREL_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KARELVariables.
        /// </summary>
        internal static string IDS_KAREL_VARIABLES {
            get {
                return ResourceManager.GetString("IDS_KAREL_VARIABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter fully qualified file name:.
        /// </summary>
        internal static string IDS_LOAD_FILE_PROMPT {
            get {
                return ResourceManager.GetString("IDS_LOAD_FILE_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load File.
        /// </summary>
        internal static string IDS_LOAD_FILE_TITLE {
            get {
                return ResourceManager.GetString("IDS_LOAD_FILE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string IDS_NO {
            get {
                return ResourceManager.GetString("IDS_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no active alarms.
        /// </summary>
        internal static string IDS_NO_ACITVE_ALARMS {
            get {
                return ResourceManager.GetString("IDS_NO_ACITVE_ALARMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Oder Number text box is empty.
        /// </summary>
        internal static string IDS_NO_FEATURE_NUMBER_DEFINED {
            get {
                return ResourceManager.GetString("IDS_NO_FEATURE_NUMBER_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  not found..
        /// </summary>
        internal static string IDS_NOT_FOUND {
            get {
                return ResourceManager.GetString("IDS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing Connected.
        /// </summary>
        internal static string IDS_NOTHING_CONNECTED {
            get {
                return ResourceManager.GetString("IDS_NOTHING_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing selected.
        /// </summary>
        internal static string IDS_NOTHING_SELECTED {
            get {
                return ResourceManager.GetString("IDS_NOTHING_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Features =.
        /// </summary>
        internal static string IDS_NUMBER_OF_FEATURES {
            get {
                return ResourceManager.GetString("IDS_NUMBER_OF_FEATURES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Trigger value.\nSubSystemCode must be in the range 0 to 255\nRequest code must be in the range 0 to 255\nPacketID must be in the range 0 to 2,000,000,000.
        /// </summary>
        internal static string IDS_PACKET_INV_TRIGGER {
            get {
                return ResourceManager.GetString("IDS_PACKET_INV_TRIGGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCIF option not installed.
        /// </summary>
        internal static string IDS_PCIF_NOT_INSTALLED {
            get {
                return ResourceManager.GetString("IDS_PCIF_NOT_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinging.
        /// </summary>
        internal static string IDS_PINGING {
            get {
                return ResourceManager.GetString("IDS_PINGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Registers.
        /// </summary>
        internal static string IDS_POSITION_REGSITERS {
            get {
                return ResourceManager.GetString("IDS_POSITION_REGSITERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRCProgram.Run.
        /// </summary>
        internal static string IDS_PROGRAM_RUN {
            get {
                return ResourceManager.GetString("IDS_PROGRAM_RUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reach?.
        /// </summary>
        internal static string IDS_Q_REACH {
            get {
                return ResourceManager.GetString("IDS_Q_REACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reachable?.
        /// </summary>
        internal static string IDS_Q_REACHABLE {
            get {
                return ResourceManager.GetString("IDS_Q_REACHABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R E S E T.
        /// </summary>
        internal static string IDS_R_E_S_E_T {
            get {
                return ResourceManager.GetString("IDS_R_E_S_E_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified region has been searched. Start over from the beginning?.
        /// </summary>
        internal static string IDS_REGION_SEARCHED {
            get {
                return ResourceManager.GetString("IDS_REGION_SEARCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ScatteredAccess object has not been intialized.
        /// </summary>
        internal static string IDS_SCATT_NOT_INITIALIZED {
            get {
                return ResourceManager.GetString("IDS_SCATT_NOT_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select .
        /// </summary>
        internal static string IDS_SELECT {
            get {
                return ResourceManager.GetString("IDS_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRRobotDemoVBNet - Selecting a robot.
        /// </summary>
        internal static string IDS_SELECTING_ROBOT {
            get {
                return ResourceManager.GetString("IDS_SELECTING_ROBOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new maximum alarm log size..
        /// </summary>
        internal static string IDS_SET_MAX_PROMPT {
            get {
                return ResourceManager.GetString("IDS_SET_MAX_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Mog Max.
        /// </summary>
        internal static string IDS_SET_MAX_TITLE {
            get {
                return ResourceManager.GetString("IDS_SET_MAX_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signals.
        /// </summary>
        internal static string IDS_SIGNALS {
            get {
                return ResourceManager.GetString("IDS_SIGNALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller is running in Cold start mode.
        /// </summary>
        internal static string IDS_START_MODE_COLD {
            get {
                return ResourceManager.GetString("IDS_START_MODE_COLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller is running in Controlled start mode.
        /// </summary>
        internal static string IDS_START_MODE_CTRL {
            get {
                return ResourceManager.GetString("IDS_START_MODE_CTRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller is running in Hot start mode.
        /// </summary>
        internal static string IDS_START_MODE_HOT {
            get {
                return ResourceManager.GetString("IDS_START_MODE_HOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller is running in Initial start mode.
        /// </summary>
        internal static string IDS_START_MODE_INIT {
            get {
                return ResourceManager.GetString("IDS_START_MODE_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller is running in an Unknown start mode.
        /// </summary>
        internal static string IDS_START_MODE_UNKNOWN {
            get {
                return ResourceManager.GetString("IDS_START_MODE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Monitoring.
        /// </summary>
        internal static string IDS_START_MONITORING {
            get {
                return ResourceManager.GetString("IDS_START_MONITORING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Monitoring.
        /// </summary>
        internal static string IDS_STOP_MONITORING {
            get {
                return ResourceManager.GetString("IDS_STOP_MONITORING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted.
        /// </summary>
        internal static string IDS_TASK_ABORTED {
            get {
                return ResourceManager.GetString("IDS_TASK_ABORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborting.
        /// </summary>
        internal static string IDS_TASK_ABORTING {
            get {
                return ResourceManager.GetString("IDS_TASK_ABORTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        internal static string IDS_TASK_IDLE {
            get {
                return ResourceManager.GetString("IDS_TASK_IDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not detect the task being created.
        /// </summary>
        internal static string IDS_TASK_NOT_CREATED {
            get {
                return ResourceManager.GetString("IDS_TASK_NOT_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not initialized).
        /// </summary>
        internal static string IDS_TASK_NOT_INITIALIZED {
            get {
                return ResourceManager.GetString("IDS_TASK_NOT_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string IDS_TASK_PAUSED {
            get {
                return ResourceManager.GetString("IDS_TASK_PAUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string IDS_TASK_RUNNING {
            get {
                return ResourceManager.GetString("IDS_TASK_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting.
        /// </summary>
        internal static string IDS_TASK_STARTING {
            get {
                return ResourceManager.GetString("IDS_TASK_STARTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This robot has .
        /// </summary>
        internal static string IDS_THIS_HAS_NUMGROUPS {
            get {
                return ResourceManager.GetString("IDS_THIS_HAS_NUMGROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Frames.
        /// </summary>
        internal static string IDS_TOOL_FRAMES {
            get {
                return ResourceManager.GetString("IDS_TOOL_FRAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPProgram.
        /// </summary>
        internal static string IDS_TP_PROGRAM {
            get {
                return ResourceManager.GetString("IDS_TP_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string IDS_TRUE {
            get {
                return ResourceManager.GetString("IDS_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        internal static string IDS_UNAVAILABLE {
            get {
                return ResourceManager.GetString("IDS_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck Read Only.
        /// </summary>
        internal static string IDS_UNCHECK_READONLY {
            get {
                return ResourceManager.GetString("IDS_UNCHECK_READONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error -.
        /// </summary>
        internal static string IDS_UNEXPECTED_ERROR {
            get {
                return ResourceManager.GetString("IDS_UNEXPECTED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **** Uninitialized *****.
        /// </summary>
        internal static string IDS_UNINIT {
            get {
                return ResourceManager.GetString("IDS_UNINIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string IDS_UNKNOWN {
            get {
                return ResourceManager.GetString("IDS_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Frames.
        /// </summary>
        internal static string IDS_USER_FRAMES {
            get {
                return ResourceManager.GetString("IDS_USER_FRAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select var by name.
        /// </summary>
        internal static string IDS_VARS_BYNAME {
            get {
                return ResourceManager.GetString("IDS_VARS_BYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string IDS_YES {
            get {
                return ResourceManager.GetString("IDS_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SQUARE_TRANSPARENT {
            get {
                object obj = ResourceManager.GetObject("SQUARE_TRANSPARENT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
